### ISSUE TITLE
Picotool unusably slow with large program (W11)

### ISSUE THREAD

**Issue by UKTailwind** [raspberrypi/picotool#105]
MMBasic creates an image which is just under a Megabyte (rp2040). elf2uf2 used to create the uf2 in a couple of seconds. picotool takes several minutes and a processor is running a maximum during this period (W11 PC with I7-12700). It does eventually complete and appears to create a valid uf2.
I believe the problem is in the creation of the dis file which is 11.4Mbytes. If I kill picotools using the task manager the UF2 is created but the dis creation fails

**Comment by will-v-pi** [comment]
Closing as duplicate #106
