### ISSUE TITLE
Support "reset" command for non BOOTSEL device with STDIO USB reset interface

### ISSUE THREAD

**Issue by kilograham** [raspberrypi/picotool#13]
SDK 1.1.0 adds (optional) support for code exposing STDIO USB to be reset via another USB vendor interface. This obviously makes sense for the the "reset" command, though we should probably add a `-f, --force` or whatever option to make this happen.

**Comment by lurch** [comment]
IIRC that new USB vendor interface allows resetting to BOOTSEL or resetting to flash boot, so perhaps picotool should expose both those options?

**Comment by kilograham** [comment]
picotool already does

**Comment by lurch** [comment]
I guess that must be only in the Graham-version? https://github.com/raspberrypi/picotool/commits/master

**Comment by kilograham** [comment]
the `picotool reboot` already supports options to specify which type of boot you want (flash boot or usb boot), has since the get go; it is in master

**Comment by lurch** [comment]
Ahh, I was getting confused by the already-existing-reboot (i.e. over PICOBOOT?) and the new-USB-vendor-reboot.
Also, I'd never thought to run `picotool help reboot` which is the **only** place where this is ever mentioned :stuck_out_tongue_winking_eye:

**Comment by lurch** [comment]
And based on our internal discussions, I wonder if `picotool reboot` also ought to have an option for "reboot into BOOTSEL mode but only enable PICOBOOT, don't enable the MSD interface" ? :shrug:
