### ISSUE TITLE
How can i correctly install picotool on Linux

### ISSUE THREAD

**Issue by erfanium** [raspberrypi/picotool#147]
I have installed picotool binary and it is available within my $PATH:
```sh
$ picotool version
picotool v2.0.0 (Linux, GNU-13.2.0, Release)
```

But every time i want build a fresh pico project, I get this warning message:

```sh
CMake Warning at /home/erfanium/Documents/pico-sdk/tools/Findpicotool.cmake:28 (message):
  No installed picotool with version 2.0.0 found - building from source

  It is recommended to build and install picotool separately, or to set
  PICOTOOL_FETCH_FROM_GIT_PATH to a common directory for all your SDK
  projects
Call Stack (most recent call first):
  /home/erfanium/Documents/pico-sdk/tools/CMakeLists.txt:138 (find_package)
  /home/erfanium/Documents/pico-sdk/src/cmake/on_device.cmake:33 (pico_init_picotool)
  /home/erfanium/Documents/pico-sdk/src/rp2040/boot_stage2/CMakeLists.txt:57 (pico_add_dis_output)
  /home/erfanium/Documents/pico-sdk/src/rp2040/boot_stage2/CMakeLists.txt:101 (pico_define_boot_stage2)
```

It says `It is recommended to build and install picotool separately`, but there is no documentation about it, How should i correctly install it?

**Comment by erfanium** [comment]
I reinstalled the picotool and now it's working.

seams the binary location should be `/usr/local/bin/picotool`, not `/usr/bin/picotool` in my case

**Comment by codebrane** [comment]
This doesn't appear to work on a raspberry pi 4:

```
which picotool
/home/pi/bin/picotool

```
```
echo $picotool_DIR
/home/pi/bin/picotool

```
```
picotool version
picotool v2.1.1 (Linux, GNU-10.2.1, Release)

```
`cmake -Dpicotool_DIR=/home/pi/bin/picotool ..`

`No installed picotool with version 2.1.1 found - building from source`

**Comment by lurch** [comment]
@codebrane I suspect you didn't follow the instructions in the `README.md` fully? You need to do `make install`, rather than just copying the `picotool` binary to a random folder, because it also installs a bunch of `*.cmake` files (which the build-system in the SDK looks for).

**Comment by codebrane** [comment]
yes thank you. It seemed a bit confusing with DIR in the name and multiple mentions of picotool in the path but the following now works:

build and install picotool:
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/pi/picotool -DPICOTOOL_FLAT_INSTALL=1 ..
make -j4
make install
```
find picotool in a project:
```
cmake -Dpicotool_DIR=/home/pi/picotool/picotool ..
make -j4
```
