### ISSUE TITLE
RP2350-E9 referenced in code and README seems to be using wrong errata specifier

### ISSUE THREAD

**Issue by jakerr** [raspberrypi/picotool#165]
It seems to me that every mention of `RP2350-E9` currently in the codebase related to ` --abs-block` should actually be:
`RP2350-E10`

See page 1347 in the Datasheet:
https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf

| | Component | Issue Code | Description |
|--------|-----------|------------|-------------|
| ❌     | GPIO      | RP2350-E9  | Increased leakage current on Bank 0 GPIO when pad input is enabled |
| ✅     | Bootrom   | RP2350-E10 | UF2 drag & drop doesn’t work with partition tables                 |

**Comment by lurch** [comment]
Duplicate of #115 ?

**Comment by will-v-pi** [comment]
Yeah, already fixed in the develop branch
