### ISSUE TITLE
picotool uf2 convert --verbose option doesn't work

### ISSUE THREAD

**Issue by richard9999999999** [raspberrypi/picotool#185]
picotool uf2 convert --verbose option doesn't work for me

**Comment by lurch** [comment]
Can you please give more details, e.g. what did you expect to happen, and what actually happened? And did you see any error messages?

**Comment by richard9999999999** [comment]
OK, if you look into elf2uf2.cpp, you see

**Comment by will-v-pi** [comment]
Merged into develop
