### ISSUE TITLE
Is picotool on brew?

### ISSUE THREAD

**Issue by Exr0n** [raspberrypi/picotool#33]
Hey everyone :wave:

I'm wondering if / where I can find and install picotool using [homebrew](https://brew.sh)?

I tried just `brew install picotool` but it could not find any casks or formulae. 

Cheers!

**Comment by lurch** [comment]
One for @aallan  :wink:

**Comment by aallan** [comment]
Sorry. It's not installable by homebrew.

**Comment by Exr0n** [comment]
Ah, thanks for the info! What's the recommended way to install on MacOS? Or do you just have to build from scratch?

**Comment by lurch** [comment]
> Or do you just have to build from scratch?

Yes, see Appendix B of https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf
