### ISSUE TITLE
No rule to install `picotool` binary

### ISSUE THREAD

**Issue by ggardet** [raspberrypi/picotool#4]
All the cmake system is in place except for the installation of `picotool` to `/usr/bin` target.
When `make install` is run, we get:
```
make: *** No rule to make target 'install'.  Stop.
```

**Comment by kilograham** [comment]
good idea; that would make sense

**Comment by aallan** [comment]
With respect to raspberrypi/pico-feedback#48 picotool should install into /usr/local/bin and not /usr/bin under macOS. Mucking about with /usr/bin on a Mac is problematic.

**Comment by ggardet** [comment]
> With respect to [raspberrypi/pico-feedback#48](https://github.com/raspberrypi/pico-feedback/issues/48) picotool should install into /usr/local/bin and not /usr/bin under macOS. Mucking about with /usr/bin on a Mac is problematic.

It should be something `%{prefix}/bin` anyway

**Comment by lurch** [comment]
Fixed by https://github.com/raspberrypi/picotool/commit/ce769705338cb57abc57d1a586983abe3a5e5199 ?

**Comment by ggardet** [comment]
> Fixed by [ce76970](https://github.com/raspberrypi/picotool/commit/ce769705338cb57abc57d1a586983abe3a5e5199) ?

Likely, but I did not try it yet.

**Comment by ggardet** [comment]
I backported ce76970 to version 1.0.1 and I confirm this fixes this issue.

**Comment by lurch** [comment]
Why did you need to backport, instead of just using the latest `develop` version?
