### ISSUE TITLE
Error building in Windows

### ISSUE THREAD

**Issue by SatoW04ld** [raspberrypi/picotool#45]
After trying to build using ninja, I get the following error.

[4/4] Linking CXX executable picotool.exe
FAILED: picotool.exe
cmd.exe /C "cd . && C:\MinGW\bin\c++.exe -O3 -DNDEBUG  CMakeFiles/picotool.dir/main.cpp.obj CMakeFiles/picotool.dir/picoboot_connection/picoboot_connection_cxx.cpp.obj CMakeFiles/picotool.dir/picoboot_connection/picoboot_connection.c.obj -o picotool.exe -Wl,--out-implib,libpicotool.dll.a -Wl,--major-image-version,0,--minor-image-version,0  C:/Users/blam/Desktop/LIBUSB/VS2019/MS32/static/libusb-1.0.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."

C:/Users/blam/Desktop/LIBUSB/VS2019/MS32/static/libusb-1.0.lib: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Thanks

**Comment by lurch** [comment]
The instructions in Appendix B of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf work (and see also Chapter 9 of the same PDF).
You're using both ninja and mingw, and I'm afraid we don't officially support either of those. (although if you _do_ manage to get things working, we'll gladly accept a PR.)
