### ISSUE TITLE
[BUG] FindLIBUSB.cmake points to an old include and library paths

### ISSUE THREAD

**Issue by NickAlvar91** [raspberrypi/picotool#52]
The [findLIBUSB.cmake](https://github.com/raspberrypi/picotool/blob/master/cmake/FindLIBUSB.cmake) file points to folders that existed in "libusb-1.0.24"
```cmake 
FIND_PATH(LIBUSB_INCLUDE_DIR libusb.h
       ***HINTS $ENV{LIBUSB_ROOT}/include/libusb-1.0***
       PATHS ${PC_LIBUSB_INCLUDEDIR} ${PC_LIBUSB_INCLUDE_DIRS})
FIND_LIBRARY(LIBUSB_LIBRARIES NAMES libusb-1.0 usb-1.0 usb
       ***HINTS $ENV{LIBUSB_ROOT}/VS2019/MS32/static***
```
libusb1.0.24 path to "libusb-1.0.lib" ( $ENV{LIBUSB_ROOT}/VS2019/MS32/static)
![image](https://user-images.githubusercontent.com/50187629/172990529-f1518287-e2ad-4173-aef6-616bb215147e.png)
 
libusb1.0.24 path to "libusb.h" ($ENV{LIBUSB_ROOT}/include/libusb-1.0)
![image](https://user-images.githubusercontent.com/50187629/172991210-884fab78-a979-4df5-b1f5-89cd1e2775f7.png)

In the version 1.0.26 (as of June 6, 2022)

- folder structure has changed
version libusb1.0.24
![image](https://user-images.githubusercontent.com/50187629/172991715-f0ac6240-5be2-45e1-be35-b8bfb38b42ec.png)
current version (libusb1.0.26)
![image](https://user-images.githubusercontent.com/50187629/172991645-2d8539ee-d62d-48a2-9109-ec8b1b0684a5.png)

- libusb.h file is now in each sub directory
![image](https://user-images.githubusercontent.com/50187629/172992127-5373bc3a-f7ba-4163-926d-5c90754ed9ce.png)

- VS2019 removed and libusb-1.0.lib under VS2015-win32
![image](https://user-images.githubusercontent.com/50187629/172992932-4a92b5b1-679a-4650-8137-fd633c2522ea.png)

**Comment by will-v-pi** [comment]
This has been fixed with picotool 2.0.0 if you download the latest libusb 1.0.27 release
