### ISSUE TITLE
How to convert a modified elf to uf2.

### ISSUE THREAD

**Issue by mytechnotalent** [raspberrypi/picotool#8]
I wanted to understand how to use the picotool to take a modified ```elf``` file and convert it to a ```uf2``` that can be dropped into the flash like a normal ```uf2```?

**Comment by kilograham** [comment]
well if you really want to you can do
picotool load foo.elf
picotool save foo.uf2

but you are probably better of using elf2uf2 from the SDK

**Comment by mytechnotalent** [comment]
@kilograham your amazing thank you for being so quick and so helpful!  I assume if I wanted to convert a uf2 to elf it would be:
```
picotool load foo.uf2
picotool save foo.elf
```

In addition is there a ```uf22elf``` as well in the SDK?  Thanks!

**Comment by kilograham** [comment]
nope we don't have any tools that save as ELF

**Comment by mytechnotalent** [comment]
Thanks again for all the help!  I was trying to find a way to work with the uf2 directly with radare2 but I believe it only works with elf.

**Comment by mytechnotalent** [comment]
Is it ok I close this out?  You have been more than helpful!!!

**Comment by kilograham** [comment]
i mean the build produces ELFs as well as UF2 ... i',m sure radare2 must work with BIN too? we can save that from picotool.

sure close away!

**Comment by mytechnotalent** [comment]
@kilograham when I try:
```picotool load foo.uf2```
I get:
```No accessible RP2040 devices in BOOTSEL mode were found but, device at bus 1m address 16 appears to be a RP2040 device in BOOTSEL mode, but pictool was unable to connect```

In addition how would I flash a .bin (separate question).

**Comment by kilograham** [comment]
if you are running on windows you need to install a driver INF. if you are on linux you probably need to be in the dialout group (or use sudo or use a udev rule).

Hopefully these are documented in the getting started book
