### ISSUE TITLE
Unable to reset pico

### ISSUE THREAD

**Issue by LandryNorris** [raspberrypi/picotool#88]
When I run `picotool.exe reboot -f -u`, I get the following error: `ERROR: Unable to locate reset interface on the device`, despite the fact that running the info command indicates `Device at bus 1, address 30 appears to be a RP2040 device with a USB serial connection, not in BOOTSEL mode. You can force reboot into BOOTSEL mode via 'picotool reboot -f -u' first.`. Running a load command does work, however, if I manually enter BOOTSEL via the button.

I am using picotool 1.1.2 and libusb 1.0.26 on Windows 11.

I have tried using both the Win32 driver and the libusb-win32 driver from Zadig.

**Comment by LandryNorris** [comment]
By adding some logging to the source for the 1.1.2 release, I can determine that picotool can find two interfaces with altsettings: one with class/subclass of 2/2, and one with class/subclass of 10/0. Neither of these matches the defined class/subclass for reset.

**Comment by Reneg973** [comment]
Having the same issue. Strongly when using PlatformIO (which uses the tool too), it works without problems. Checking the log (macOS) shows the following:
Forcing reset using 1200bps open/close on port /dev/cu.usbmodem11301

Using picotool shows:
"No accessible RP2040 devices in BOOTSEL mode were found.

but:

Device at bus 1, address 4 appears to be a RP2040 device with a USB serial connection, so consider
    -f to force the reboot."

Now using the proposed command line shows:
"ERROR: Unable to locate reset interface on the device"

**Comment by lurch** [comment]
You need to ensure that `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` is enabled, which adds the reset interface. See Appendix B in https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf

> Forcing reset using 1200bps open/close on port /dev/cu.usbmodem11301

I guess that indicates that `PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE` **is** enabled. Maybe that implies that PlatformIO has disabled `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` for some reason?

**Comment by Reneg973** [comment]
> You need to ensure that `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` is enabled, which adds the reset interface. See Appendix B in https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf
> 
> > Forcing reset using 1200bps open/close on port /dev/cu.usbmodem11301
> 
> I guess that indicates that `PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE` **is** enabled. Maybe that implies that PlatformIO has disabled `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` for some reason?

What I mean is PlatformIO (with Arduino) uses picotool to reset the Pico into BOOTSEL for uploading the uf2. So uploading via VSCode with PlatformIO does everything automatically. But when building my app with pico-sdk (No platformIO nor Arduino), I first have to reconnect Pico while pressing BOOTSEL. I would like to prevent this.

**Comment by lurch** [comment]
> What I mean is PlatformIO (with Arduino) uses picotool (or I'm wrong?) to reset the Pico into BOOTSEL for uploading the uf2.

Your log message indicates that PlatformIO is rebooting the Pico by changing the baud rate of the USB-serial device, which isn't something that picotool does itself.

> But when building my app with pico-sdk (No platformIO nor Arduino), I first have to reconnect Pico while pressing BOOTSEL. I would like to prevent this.

Have you got stdio_usb enabled in your CMakeLists.txt ? See Chapter 4 in https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf

**Comment by Reneg973** [comment]
> Your log message indicates that PlatformIO is rebooting the Pico by changing the baud rate of the USB-serial device, which isn't something that picotool does itself.

Ok understood. I thought the message "use -f to force the reboot" would tell me it does that.

**Comment by lurch** [comment]
> I thought the message "use -f to force the reboot" would tell me it does that.

Copied from the README.md for this project:
```
        -f, --force
            Force a device not in BOOTSEL mode but running compatible code to reset so the command can be executed. After executing
            the command (unless the command itself is a 'reboot') the device will be rebooted back to application mode
        -F, --force-no-reboot
            Force a device not in BOOTSEL mode but running compatible code to reset so the command can be executed. After executing
            the command (unless the command itself is a 'reboot') the device will be left connected and accessible to picotool, but
            without the RPI-RP2 drive mounted
```
i.e. if your Pico is _already_ in BOOTSEL mode then the `-f` flag isn't necessary; but if your Pico is currently running user-code (and **if** you have both stdio_usb and the custom reset interface enabled), then you need to use the `-f` flag, and picotool will then use the custom reset-interface to reboot your Pico into BOOTSEL mode, before doing whatever else it is that you asked picotool to do. (I hope that all makes sense!)

**Comment by Reneg973** [comment]
Yes, but you already mentioned the point I was talking about:
> (and if you have both stdio_usb and the custom reset interface enabled)

If PlatformIO is able to reboot the Pico, even if it is not in BOOTSEL mode nor has these interfaces enabled, I would expect Picotool to be able to handle this too.

**Comment by lurch** [comment]
As already mentioned, it appears that PlatformIO (which I've not used myself) is using the `PICO_STDIO_USB_ENABLE_RESET_VIA_BAUD_RATE` feature (whereby it changes the baud-rate of the stdio_usb connection to `PICO_STDIO_USB_RESET_MAGIC_BAUD_RATE`).
If you want `picotool` to be able to do this baud-rate twiddling too, you should probably open a separate issue for that.

**Comment by dmo9** [comment]
Also getting the same issues with picotool where the f flag is not working on linux:

![image](https://github.com/raspberrypi/picotool/assets/28460065/67214d33-2aa2-45ed-8e0b-1f0f1121fcf3)

I have confirmed that `PICO_STDIO_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE` is set as per the SDK default.

**Comment by lurch** [comment]
@dmo9 Have you tried using `sudo`? (or whatever the ArchLinux equivalent is)

**Comment by dmo9** [comment]
> @dmo9 Have you tried using `sudo`? (or whatever the ArchLinux equivalent is)

No difference with sudo. Per the picotool documentation, it states the flag should work with "compatible" code, but there is no definition of what compatible code is. My code does call `stdio_init_all()` and enables the USB port via  `pico_enable_stdio_usb(nasa 1)` in CMakeLists.txt

Interestingly, when flashing with picoprobe, which works fine, I get the following message:
`Warn : could not read product string for device 0x2e8a:0x000a: Operation timed out
`

After a really light dive into picotool's source code, I noticed that picotool's error message probably from the following function on line 1584 of main.cpp:
`string missing_device_string(bool wasRetry)`

Could this be the root cause of the issue?

**Comment by lurch** [comment]
If you want to do a slightly deeper dive, you should probably take a look at https://github.com/raspberrypi/pico-sdk/pull/197 and https://github.com/raspberrypi/picotool/pull/23

**Comment by dmo9** [comment]
Ok, I figured out the problem: incompatible code. My code was exiting before picotool could send it commands. I suggest that the definition of compatible code is added to this repo's documentation.

main.c:
```
#include "pico/stdio_usb"
int main()
{
    stdio_usb_init();
    while(true)
    {
        // your code here
    }
}
```

CMakeLists.txt:
```
pico_enable_stdio_usb(<yourProjectName> 1)
```

**Comment by tempelmann** [comment]
> #include "pico/stdio_usb"

For me, I had to change it to:

    #include "pico/stdio_usb.h"

> CMakeLists.txt:
> `pico_enable_stdio_usb(<yourProjectName> 1)`

Or, if you're basing your CMakeLists.txt on the official examples:

    pico_enable_stdio_usb($NAME 1)

Still, this doesn't help in my case where I'm running any "pico-example" such as the picow_blink.uf2, even after making these changes.

When using micropython, "picotool reboot -u -f" does work, OTOH.

**Comment by dmo9** [comment]
Good call on the import. I don't remember what libraries I had linked but I agree that it should be included in the documentation. I agree that main cannot return; that's why my code was within an infinite loop.

**Comment by will-v-pi** [comment]
> Ideally, the Pico should reboot into BOOTSEL mode automatically when main() returns, even. I wonder how I can accomplish that - googling for this is difficult because all the results turn up how to reset the Pico with the button press.

You can set `PICO_ENTER_USB_BOOT_ON_EXIT` to do this (eg with `target_compile_definitions(my_target PRIVATE PICO_ENTER_USB_BOOT_ON_EXIT=1` in your CMakeLists.txt)

We can add a definition of compatible code to the readme - the definition being simply code that
- Uses stdio_usb
- Is running (ie hasn't returned)

**Comment by tempelmann** [comment]
> You can set `PICO_ENTER_USB_BOOT_ON_EXIT` to do this (eg with `target_compile_definitions(my_target PRIVATE PICO_ENTER_USB_BOOT_ON_EXIT=1` in your CMakeLists.txt)

Good to know. I wish these things were mentioned in the "Getting started" docs on the Raspi website, because I think they're essential for using the SDK. But those pages don't even have a feedback link.

> We can add a definition of compatible code to the readme - the definition being simply code that
> 
> * Uses stdio_usb
> * Is running (ie hasn't returned)

Thank you.

Please consider making this easier for newbies like me and mention that the lib to include in the MakeLists is then call "pico_stdio_usb", and that one needs to activate either that or the stdio lib so that this works, e.g. by showing examples like @dmo9 did here, along with my notes.

**Comment by will-v-pi** [comment]
You don't need `pico_stdio_usb` in your CMakeLists.txt file - you just need `pico_stdlib` and then to add `pico_enable_stdio_usb(<yourTargetName> 1)` to that file and call `stdio_init_all()` from your binary (see the [hello_usb](https://github.com/raspberrypi/pico-examples/tree/master/hello_world/usb) example)

I'll make that clear in the readme

**Comment by dmo9** [comment]
A bit of clarification to the newer people for why I was including pico_stdio_usb and stdio_usb_init()
 rather than pico_stdlib:

stdio_usb_init() is a wrapper function that initializes all standard IO(uart & USB) but since my application only uses usb, that’s all I initialized.

**Comment by lurch** [comment]
> Huh, after some more testing, it seems that if the `main()` function returns, then the reset via picotool fails. If I keep the code looping instead of returning from main, the reset works. That's an odd behavior but important information.

This is because if your `main()` exits / returns, then the USB-code (TinyUSB) on the RP2040 is no longer running, and so your device "disappears" from the list of USB-devices visible to your main computer.

**Comment by will-v-pi** [comment]
Added to the [readme](https://github.com/raspberrypi/picotool?tab=readme-ov-file#forced-reboots)

**Comment by heyitsmeyo** [comment]
Hello , whenever you get that error message of picotool  , next time try to do this: 

In your c file , import the stidio_usb.h library and write stidio_init_all() in the main function 

In the CMakeLists.txt : add this following line : pico_add_enable_usb(project name 1) 

By doing this , you would be able to flash any uf2 file into the pico without any issues, 


And by the way , I made a pico sdk project that can let you reset your pico into storage mode 


Good luck

**Comment by frak0d** [comment]
After some headbanging I found the reason for this error in my case on Arduino IDE:

**If last time, the pico was flashed using UF2 mode, then picotool fails to reset.**

solution for this is to manually enter BOOTSEL mode for the **first time** you use picotool. For any subsequent flashes after that reset works correctly.
