### ISSUE TITLE
Build instructions missing from README for Linux / MacOS

### ISSUE THREAD

**Issue by erichiggins** [raspberrypi/picotool#90]
The [README file](https://github.com/raspberrypi/picotool/blob/master/README.md) only lists instructions for how to install the dependencies needed in order to build picotool, but not the actual build commands. The Windows section appears more robust in that regard though those instructions may not work for the Linux/MacOS environments.

**Comment by aallan** [comment]
See Appendix B of "[Getting started with Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf)". The README isn't the documentation.

**Comment by will-v-pi** [comment]
Added with picotool 2.0.0
