### ISSUE TITLE
Why PICO_SDK_PATH is needed? How to deal with projects where pico-sdk repo is a submodule?

### ISSUE THREAD

**Issue by brizzolazzi** [raspberrypi/picotool#98]
I need to build a vscode devcontainer containing picotool and other stuff. pico-sdk instead should not be present, and thus nor the PICO_SDK_PATH. The reason is that pico-sdk should be a git submodule of my repo.
How to deal with this kind of scenario?

Many thanks in advance.

**Comment by kilograham** [comment]
If it is in a submodule, just set PICO_SDK_PATH to point to it in your parent CMakeLists.txt

**Comment by brizzolazzi** [comment]
The docker image does not contain pico-sdk but should contain picotool binary. Instead any repo has its own submodule in a different path.
In this scenario, during the build process of the docker image, the PICO_SDK_PATH Is not available.

**Comment by brizzolazzi** [comment]
The docker image does not contain any git repository.

**Comment by lurch** [comment]
> The docker image does not contain pico-sdk but should contain picotool binary.

I guess in that case you'll need to build the picotool binary outside of the docker container, and then copy it into the docker container afterwards.

**Comment by kilograham** [comment]
Anyways, best to ask questions here https://forums.raspberrypi.com/viewforum.php?f=145
